### ISSUE TITLE
Как сформировать запрос к adriver api средствами js?

### ISSUE THREAD

**Issue by slavent** [webdeskltd/adriver#1]
привет, пытаюсь обратиться. Север не отвечает

в консоли:
XMLHttpRequest cannot load https://api.adriver.ru/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '***' is therefore not allowed access.

$.ajax({
			method: "GET",
			url: "https://api.adriver.ru/login",
			contentType: "application/atom+xml",
			headers: { "X-Auth-Login": "***", "X-Auth-Passwd": "***" },
			crossDomain: true,
			success: function( data ){
				console.log( data );
			},
			error: function ( a, b, c ) {
				console.log( a );
			}
		})

В чем может быть проблема?

**Comment by monoflash** [comment]
Данный вопрос никак не связан с библиотекой, не стоило его тут публиковать.

Если отвечать на ваш вопрос, то у вас не получится никогда из браузера работать с API, так как все ваши запросы к API считаются кросс-доменными, а скрипт выполняющий данные запросы должен получить разрешение на выполнение кросс-доменных запросов.

Если вы знаете язык Go (golang), то воспользуйтесь нашей библиотекой, сделайте серверную часть и работайте с API adriver через серверную часть, которую надо разместить на том же сервере на котором размещён ваш js скрипт.
Если вы не знаете Go, то можете на node.js написать свою библиотеку и свою серверную часть для работы с API adriver.
